import "./globals.css";
import { Header } from "./Components/Header";
import InfoBar from "./Components/InfoBar";
import { generalSans } from "./fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${generalSans.variable} antialiased font-sans`}>
        <InfoBar />
        <Header />
        {children}
      </body>
    </html>
  );
}
